// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJHYMPdkQ4lPDaI8itOiyA4yXLL3gMTvM',
    appId: '1:8163762239:web:37545ebbd546af9af6d88a',
    messagingSenderId: '8163762239',
    projectId: 'instagram-clone-77329',
    authDomain: 'instagram-clone-77329.firebaseapp.com',
    storageBucket: 'instagram-clone-77329.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASmZyDXYW_3-snDgzTp8FjCE81q7pP6PY',
    appId: '1:8163762239:android:061cb970363dd54bf6d88a',
    messagingSenderId: '8163762239',
    projectId: 'instagram-clone-77329',
    storageBucket: 'instagram-clone-77329.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEdtyaNrXrPB5-KLSunWIwFsJ0-eWVxSs',
    appId: '1:8163762239:ios:7d079c6d7e376324f6d88a',
    messagingSenderId: '8163762239',
    projectId: 'instagram-clone-77329',
    storageBucket: 'instagram-clone-77329.appspot.com',
    iosBundleId: 'com.example.instgramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEdtyaNrXrPB5-KLSunWIwFsJ0-eWVxSs',
    appId: '1:8163762239:ios:28bc413c79d3b0fef6d88a',
    messagingSenderId: '8163762239',
    projectId: 'instagram-clone-77329',
    storageBucket: 'instagram-clone-77329.appspot.com',
    iosBundleId: 'com.example.instgramClone.RunnerTests',
  );
}
